### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by chagiko** [VisionICLab/SwinFuSR#4]
Hello!
I am currently working on a project related to thermal infrared super-resolution, and I noticed that your work involves the PBVS2024 dataset. Since the PBVS2024 competition has already ended, I am unable to access the dataset through the competition platform.
Could you kindly let me know if there is any way to access the PBVS2024 dataset?

**Comment by cy-4** [comment]
Hello !
Thank you for your interest. I think you can contact the organisers to get access to all the data.
That's what I did last year, and it worked.
